/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_ll_demo02_jni_NDKJniUtils.h>
#include <jni.h>
/* Header for class com_example_ll_demo02_jni_NDKJniUtils */

#ifndef _Included_com_example_ll_demo02_jni_NDKJniUtils
#define _Included_com_example_ll_demo02_jni_NDKJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ll_demo02_jni_NDKJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ll_demo02_jni_NDKJniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
